### ISSUE TITLE
Use kotlin poet to generate koltin files from gir files.

### ISSUE THREAD

**Issue by harisvsulaiman** [kropp/kotlin-native-gtk#1]
From the source code, i see that you are creating a map of the gir file, I don't know much about gtk or gir for that matter, but is the project headed to the generation of kotlin files from gir?

Would https://github.com/square/kotlinpoet this be useful

**Comment by kropp** [comment]
I've seen `kotlinpoet`, but don't like their API at the moment.
As long as generated Kotlin code is very simple, I'll stick to string templates.
I will reconsider this in the future.

**Comment by harisvsulaiman** [comment]
Wouldnt the DSL discussed in the blog be easily generated with a library like `kotlinpoet`?
I'm very much interested in bringing kotlin and its DSL to Linux desktop app building.

**Comment by kalikiana** [comment]
Apparently KotlinPoet was adopted afterall despite this issue being seemingly closed after discarding the idea: https://github.com/kropp/kotlin-native-gtk/commit/51035c63dc8cee288d1e3ecdf2c747fd5a20bc8d

**Comment by kropp** [comment]
@kalikiana I've explained everything in a [comment above](https://github.com/kropp/kotlin-native-gtk/issues/1#issuecomment-317077393).
