### ISSUE TITLE
Maven Upload

### ISSUE THREAD

**Issue by Foso** [kropp/kotlin-native-gtk#10]
Hi @kropp ,
thank you for the bindings. Are you planning to upload it to Maven Central?

**Comment by kropp** [comment]
There are still many issues with them, I don't feel they are ready to be published yet.

**Comment by kavan-mevada** [comment]
Yahh lots of issues. Can you properly show example using threads or coroutines with gtk UI update. gtk_main is blocking fun. Can you show how to do background task and async task with coroutines and update gtk UI on end of task

**Comment by Foso** [comment]
> There are still many issues with them, I don't feel they are ready to be published yet.

Ok, no problem, i understand that  :+1: , i didn't know about the issues  .
