### ISSUE TITLE
Missing file from source code

### ISSUE THREAD

**Issue by lucasvsme** [kropp/kotlin-native-gtk#2]
Could you provide some guidance on how to use the code? The `main` method expects a file named `gtk.xml`, but it's not clear what this file should be or how to get it.

**Comment by kropp** [comment]
It's a file from GObject Introspection https://developer.gnome.org/gi/
But anyway the code is not yet compilable. I'm now rewriting it from scratch.

**Comment by lucasvsme** [comment]
Thank you for the clarification, @kropp.
