### ISSUE TITLE
GObject Introspection Process

### ISSUE THREAD

**Issue by napperley** [kropp/kotlin-native-gtk#5]
Looks as though this project uses the [GObject Introspection](https://gi.readthedocs.io/en/latest/) system. Is there a separate project used to generate the Kotlin bindings for this project? How is GObject Introspection being used to generate the Kotlin Gtk3 bindings?

**Comment by napperley** [comment]
Alberto Ruiz (one of the Gnome core contributors) was looking at the repository and mentioned that it looked as though GObject Introspection wasn't being used (https://siliconislandblog.wordpress.com/2016/10/31/thoughts-on-dx-gnome-and-rust/comment-page-1/#comment-1597). Are the GTK bindings being created manually?

**Comment by kropp** [comment]
Hi @napperley!
I do use GObject Introspection to generate these bindings. The source code of the generator is not yet published, because it is ugly :( I need to rewrite it.

**Comment by realh** [comment]
@kropp How committed are you to rewriting and releasing a good quality kotlin-native gi bindings tool? I would really like something like that so I can rewrite roxterm in kotlin (so I would need bindings for vte as well as gtk), and I have started writing one myself. But I feel like the size of the task is greater than my motivation, so it would be great if there was such a tool already. Maybe I can help with yours?

**Comment by kropp** [comment]
@realh I've imported the generator code. It isn't perfect and the resulting code needs some cleanup, and tests are also missing, but it's a starting point.
I'm going to refine it in the coming weeks.
